version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 762157732118.dkr.ecr.<your-region>.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t my-static-site .
      - docker tag my-static-site:latest 762157732118.dkr.ecr.us-east-1.amazonaws.com/mysamplewebsite:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 762157732118.dkr.ecr.us-east-1.amazonaws.com/mysamplewebsite:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"my-static-container","imageUri":"%s"}]' 762157732118.dkr.ecr.us-east-1.amazonaws.com/mysamplewebsite:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
